const vehiclesTableData = [
    {
        id: 1,
        name: 'Lorem',
        lastUpdate: 'Sep 20, 2021',
        place: 'pretium',
        status: false,
    },
    {
        id: 2,
        name: 'Lorem',
        lastUpdate: 'Jun 26, 2022',
        place: 'vitae',
        status: true,
    },
    {
        id: 3,
        name: 'Lorem',
        lastUpdate: 'Feb 9, 2022',
        place: 'dolor,',
        status: false,
    },
    {
        id: 4,
        name: 'Lorem',
        lastUpdate: 'Dec 13, 2022',
        place: 'ultrices.',
        status: true,
    },
    {
        id: 5,
        name: 'Lorem',
        lastUpdate: 'Jan 24, 2022',
        place: 'Donec',
        status: false,
    },
    {
        id: 6,
        name: 'Lorem',
        lastUpdate: 'Jan 21, 2023',
        place: 'amet',
        status: false,
    },
    {
        id: 7,
        name: 'Lorem',
        lastUpdate: 'Nov 5, 2022',
        place: 'ut',
        status: false,
    },
    {
        id: 8,
        name: 'Lorem',
        lastUpdate: 'Jul 8, 2022',
        place: 'Duis',
        status: false,
    },
    {
        id: 9,
        name: 'Lorem',
        lastUpdate: 'Feb 25, 2023',
        place: 'libero.',
        status: false,
    },
    {
        id: 10,
        name: 'Lorem',
        lastUpdate: 'Aug 19, 2022',
        place: 'sociosqu',
        status: true,
    },
    {
        id: 11,
        name: 'Lorem',
        lastUpdate: 'Jan 21, 2023',
        place: 'amet',
        status: false,
    },
    {
        id: 12,
        name: 'Lorem',
        lastUpdate: 'Nov 5, 2022',
        place: 'ut',
        status: false,
    },
    {
        id: 13,
        name: 'Lorem',
        lastUpdate: 'Jul 8, 2022',
        place: 'Duis',
        status: false,
    },
    {
        id: 14,
        name: 'Lorem',
        lastUpdate: 'Feb 25, 2023',
        place: 'libero.',
        status: false,
    },
    {
        id: 15,
        name: 'Lorem',
        lastUpdate: 'Aug 19, 2022',
        place: 'sociosqu',
        status: true,
    },
    {
        id: 16,
        name: 'Lorem',
        lastUpdate: 'Jan 21, 2023',
        place: 'amet',
        status: false,
    },
    {
        id: 17,
        name: 'Lorem',
        lastUpdate: 'Nov 5, 2022',
        place: 'ut',
        status: false,
    },
    {
        id: 18,
        name: 'Lorem',
        lastUpdate: 'Jul 8, 2022',
        place: 'Duis',
        status: false,
    },
    {
        id: 19,
        name: 'Lorem',
        lastUpdate: 'Feb 25, 2023',
        place: 'libero.',
        status: false,
    },
    {
        id: 20,
        name: 'Lorem',
        lastUpdate: 'Aug 19, 2022',
        place: 'sociosqu',
        status: true,
    },
    {
        id: 21,
        name: 'Lorem',
        lastUpdate: 'Jan 21, 2023',
        place: 'amet',
        status: false,
    },
    {
        id: 22,
        name: 'Lorem',
        lastUpdate: 'Nov 5, 2022',
        place: 'ut',
        status: false,
    },
    {
        id: 23,
        name: 'Lorem',
        lastUpdate: 'Jul 8, 2022',
        place: 'Duis',
        status: false,
    },
    {
        id: 24,
        name: 'Lorem',
        lastUpdate: 'Feb 25, 2023',
        place: 'libero.',
        status: false,
    },
    {
        id: 25,
        name: 'Lorem',
        lastUpdate: 'Aug 19, 2022',
        place: 'sociosqu',
        status: true,
    },
];

export default vehiclesTableData;
